# Generated by Django 6.0.3 on 2026-04-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='chat_files/%Y/%m/%d/')),
                ('original_name', models.CharField(max_length=255)),
                ('room_name', models.CharField(max_length=255)),
                ('uploaded_by', models.CharField(max_length=150)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('size', models.IntegerField()),
            ],
        ),
    ]
